apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-monitor
  labels:
    release: dashboard
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
  - port: metrics
