apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.6
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: postgres-credential
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db-pvc
